apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ns-project
  name: front-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: img-pv # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi