apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: ns-project
  name: back-dep
  labels:
    app: back-dep
spec:
  replicas: 4
  selector:
    matchLabels:
      app: back-dep
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: cpu-usage-monitor
          args:
          - name: duration
            value: "10m"  # Wait 10 minutes for analysis
  template:
    metadata:
      labels: 
        app: back-dep
    spec:
      containers:
      - name: backend-app
        image: mo3mo3/backend:v4
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: back-config
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /todos
            port: 8080
        livenessProbe:
          initialDelaySeconds: 25
          periodSeconds: 5
          httpGet:
            path: /todos
            port: 8080
