apiVersion: v1
kind: Service
metadata:
  namespace: ns-project
  name: backend-svc
spec:
  selector:
    app: back-dep
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 8080
  type: ClusterIP
  