apiVersion: apps/v1
kind: Deployment
metadata:
  name: logapp-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logapp
  template:
    metadata:
      labels:
        app: logapp
    spec:
      containers:
        - name: logapp
          image: mo3mo3/log_output:v1