apiVersion: v1
kind: Service
metadata:
  namespace: ns-project
  name: front-svc
spec:
  selector:
    app: front-dep
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 3000
  type: ClusterIP
  