apiVersion: v1
kind: Service
metadata:
  namespace: ns-pong-output
  name: pingpong-svc
spec:
  selector:
    app: pingpong-dep
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 8080
  type: ClusterIP
  