apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: ns-pong-output
  name: pingpong-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pingpong-dep
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50