apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummysite-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummysite-controller
  template:
    metadata:
      labels:
        app: dummysite-controller
    spec:
      serviceAccountName: dummysite-controller-sa
      containers:
      - name: dummysite-controller
        image: mo3mo3/dummysite:v1
        ports:
        - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: dummysite-svc
spec:
  type: NodePort 
  selector:
    app: dummysite-controller
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5555