apiVersion: v1
kind: Service
metadata:
  namespace: ns-pong-output
  name: log-svc
spec:
  selector:
    app: log-dep
  ports:
    - protocol: TCP
      port: 2345
      targetPort: 8080
  type: ClusterIP
  