apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-dep
  labels:
    app: back-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-dep
  template:
    metadata:
      name: back-dep
      labels:
        app: back-dep
    spec:
      containers:
        - name: backend-app
          image: PROJECT/IMAGE
          envFrom:
            - configMapRef:
                name: back-config
          resourses:
            limits:
              cpu: "150m"
              memory: "100Mi"

      