apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: front-claim # name of the volume claim, this will be used in the deployment
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi