apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-dep
  labels:
    app: log-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-dep
  template:
    metadata:
      name: log-dep
      labels:
        app: log-dep
    spec:
      volumes:
        - name: shared-count
          persistentVolumeClaim:
            claimName: count-claim

      containers:
        - name: log-app
          image: mo3mo3/log-app:v3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/app/shared"
              name: shared-count


      