apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-wiki
        image: alpine:3.20
        command: ['sh', '-c', 'wget -qO- https://en.wikipedia.org/wiki/Kubernetes > /www/index.html']
        volumeMounts:
        - name: html
          mountPath: /www
      - name: random-curler
        image: alpine:3.20
        command: ['sh', '-c', 'wget -qO- https://en.wikipedia.org/wiki/Special:Random > /www/index.html && sleep 600']
        restartPolicy: Always
        volumeMounts:
        - name: html
          mountPath: /www
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        emptyDir: {}