apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourly-todos
  namespace: ns-project
spec:
  schedule: "0 * * * *" # Runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-generator
              image: mo3mo3/todo-generator:v1
              env:
                - name: BACKEND_URL
                  value: "http://backend-svc:2222/todos"
          restartPolicy: OnFailure
