apiVersion: v1
kind: Service
metadata:
  namespace: ns-project
  name: db-svc
  labels:
    app: db-svc
spec:
  ports:
  - port: 5432
    name: database
  clusterIP: None
  selector:
    app: db-stateful